### ISSUE TITLE
Create endpoint for list of users

### ISSUE THREAD

**Issue by dbetka** [dbetka/harcmap#290]
TODO:
- [ ] backend endpoint
- [ ] front-end API handling

I need list of users to show its scores on admin panel.

Require data for views:
- userTeam
- collectedPointsIds
- user should be belong to event where I am (or eventId to check this on front-end)

**Comment by HenoJurek** [comment]
Sory. Powieliłem zadanie XD
https://github.com/dbetka/harcmap/issues/304

Przenoszę opis do nowego
