### ISSUE TITLE
Server always give activation-wrong

### ISSUE THREAD

**Issue by dbetka** [dbetka/harcmap#410]
https://harcmap.henouser.pl/activation-wrong
Error appears only on server - local version works properly.

Data used while test:
```
user: 'dominik.betka@zhp.net.pl',
password: 'asdASD123',
userTeam: 'Testowy team',
eventId: 'ks6f',
```

Similar bug appears if you try to use link to change password.

This bug appears sometimes and it's difficult to reproduce.

**Comment by HenoJurek** [comment]
It looks like account is already active. Thats why you see error

**Comment by dbetka** [comment]
Error appears only for outlook accounts. Outlook has own proxy link what makes error.
